camera:
  width: 640
  height: 480
  fps: 30
  use_auto_exposure: false
  exposure: 50
  depth_width: 640
  depth_height: 480
  depth_fps: 30
  depth_window: 5
  min_depth_mm: 200
  max_depth_mm: 800
spiral:
  a: 20.0
  b: 30.0
  turns: 2
  theta_step: 0.01
  line_thickness: 5
  color_bgr:
  - 40
  - 220
  - 40
  start_radius_px: 18
  end_radius_px: 18
dwell:
  StartRadiusPx: 18
  StartDwellSec: 1.0
  EndRadiusPx: 18
  StopDwellSec: 1.0
  hysteresis_px: 6
mediapipe:
  model_complexity: 1
  detection_confidence: 0.9
  tracking_confidence: 0.9
  ema_alpha: 1.0
color:
  hsv_low:
  - 57
  - 155
  - 29
  hsv_high:
  - 137
  - 255
  - 139
  morph_kernel: 3
  min_area: 60
  use_flow_fallback: false
  flow_win: 15
  flow_max_level: 2
  use_depth_filter: true
led:
  hsv_low:
  - 0
  - 100
  - 150
  hsv_high:
  - 20
  - 255
  - 255
  brightness_threshold: 20
  morph_kernel: 3
  min_area: 20
experiment:
  methods_order:
  - mp
  - hsv
  trials_per_method: 1
  save_preview: false
  output_dir: runs
  metronome_bpm: 0
  max_jump_px: 60
tremor_analysis:
  band_low_hz: 4.0
  band_high_hz: 10.0
stereo_3d:
  target_depth_m: 0.5
  disparity_offset_px: -600
show_live_preview: true
